name: NodeJS CI
on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 9
      - uses: actions/setup-node@v4.0.2
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: check code style
        run: pnpm run prettier:check
      - name: lint code
        run: pnpm run lint
