name: Renovate

on:
  workflow_dispatch:
    inputs:
      log-level:
        description: Log level
        required: true
        default: INFO
        type: choice
        options:
          - TRACE
          - DEBUG
          - INFO
          - WARN
          - ERROR

concurrency:
  group: renovate

# All permissions come from actions/create-github-app-token
permissions: {}

env:
  LOG_LEVEL: ${{ github.event.inputs.log-level }}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: create-github-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      # Checkout the repository so Renovate can get its configuration
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: renovatebot/github-action@9ba84f1ade243f8c2ce5b223df61cf23dc094584 # v43.0.13
        with:
          configurationFile: .github/renovate.global.json
          token: ${{ steps.create-github-app-token.outputs.token }}
          requireConfig: optional
          onboarding: false
